# Don't print a new line at the start of the prompt
add_newline = false

[aws]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
disabled = false

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = false

[golang]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[line_break]
disabled = true

[lua]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[username]
disabled = true

[zig]
disabled = true
